# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.9.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class MinScores(BaseModel):
    """
    Optional per-stage score floors for recall (all inclusive >=).  ``semantic`` and ``keyword`` are **per-arm retrieval-level** cutoffs pushed into the individual SQL query arms (overriding the global ``semantic_min_similarity`` / ``bm25_min_score`` config for this request), so they prune weak matches within each arm before fusion. Because recall merges candidates across multiple arms (semantic, keyword, graph, temporal), a result clearing one arm's threshold enters fusion even if absent or below floor in another arm (i.e. not a cross-arm same-result intersection).  ``reranker`` and ``final`` are **post-ranking filters** applied to all scored candidates after fusion and reranking, filtering out results that do not satisfy the threshold.  Any field left None imposes no floor; all-None (the default) means no score filtering.
    """ # noqa: E501
    semantic: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    keyword: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    reranker: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    final: Optional[Union[Annotated[float, Field(strict=True, ge=0.0)], Annotated[int, Field(strict=True, ge=0)]]] = None
    __properties: ClassVar[List[str]] = ["semantic", "keyword", "reranker", "final"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MinScores from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if semantic (nullable) is None
        # and model_fields_set contains the field
        if self.semantic is None and "semantic" in self.model_fields_set:
            _dict['semantic'] = None

        # set to None if keyword (nullable) is None
        # and model_fields_set contains the field
        if self.keyword is None and "keyword" in self.model_fields_set:
            _dict['keyword'] = None

        # set to None if reranker (nullable) is None
        # and model_fields_set contains the field
        if self.reranker is None and "reranker" in self.model_fields_set:
            _dict['reranker'] = None

        # set to None if final (nullable) is None
        # and model_fields_set contains the field
        if self.final is None and "final" in self.model_fields_set:
            _dict['final'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MinScores from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "semantic": obj.get("semantic"),
            "keyword": obj.get("keyword"),
            "reranker": obj.get("reranker"),
            "final": obj.get("final")
        })
        return _obj


