/*
Hindsight HTTP API

HTTP API for Hindsight

API version: 0.8.5
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package hindsight

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BulkDeleteMemoriesRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BulkDeleteMemoriesRequest{}

// BulkDeleteMemoriesRequest Memory-unit IDs to irreversibly delete from one bank.
type BulkDeleteMemoriesRequest struct {
	// Memory-unit UUIDs to permanently delete. Every unit must belong to the bank in the URL.
	UnitIds []string `json:"unit_ids"`
}

type _BulkDeleteMemoriesRequest BulkDeleteMemoriesRequest

// NewBulkDeleteMemoriesRequest instantiates a new BulkDeleteMemoriesRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBulkDeleteMemoriesRequest(unitIds []string) *BulkDeleteMemoriesRequest {
	this := BulkDeleteMemoriesRequest{}
	this.UnitIds = unitIds
	return &this
}

// NewBulkDeleteMemoriesRequestWithDefaults instantiates a new BulkDeleteMemoriesRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBulkDeleteMemoriesRequestWithDefaults() *BulkDeleteMemoriesRequest {
	this := BulkDeleteMemoriesRequest{}
	return &this
}

// GetUnitIds returns the UnitIds field value
func (o *BulkDeleteMemoriesRequest) GetUnitIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.UnitIds
}

// GetUnitIdsOk returns a tuple with the UnitIds field value
// and a boolean to check if the value has been set.
func (o *BulkDeleteMemoriesRequest) GetUnitIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.UnitIds, true
}

// SetUnitIds sets field value
func (o *BulkDeleteMemoriesRequest) SetUnitIds(v []string) {
	o.UnitIds = v
}

func (o BulkDeleteMemoriesRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BulkDeleteMemoriesRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["unit_ids"] = o.UnitIds
	return toSerialize, nil
}

func (o *BulkDeleteMemoriesRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"unit_ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBulkDeleteMemoriesRequest := _BulkDeleteMemoriesRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBulkDeleteMemoriesRequest)

	if err != nil {
		return err
	}

	*o = BulkDeleteMemoriesRequest(varBulkDeleteMemoriesRequest)

	return err
}

type NullableBulkDeleteMemoriesRequest struct {
	value *BulkDeleteMemoriesRequest
	isSet bool
}

func (v NullableBulkDeleteMemoriesRequest) Get() *BulkDeleteMemoriesRequest {
	return v.value
}

func (v *NullableBulkDeleteMemoriesRequest) Set(val *BulkDeleteMemoriesRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBulkDeleteMemoriesRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBulkDeleteMemoriesRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBulkDeleteMemoriesRequest(val *BulkDeleteMemoriesRequest) *NullableBulkDeleteMemoriesRequest {
	return &NullableBulkDeleteMemoriesRequest{value: val, isSet: true}
}

func (v NullableBulkDeleteMemoriesRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBulkDeleteMemoriesRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


